### ISSUE TITLE
-f Parameter only work for Top100 Coins

### ISSUE THREAD

**Issue by dArkjON** [RDCH106/pycoinmon#9]
I try to gather some Infos from Coins with a Rank +100 but the CMC ticker v1
API only Provide the first 100 Coins on a normal call. Any solutions here ?

**Comment by RDCH106** [comment]
Yes!

You need use `-t` or `--top` [option](https://github.com/RDCH106/pycoinmon#options) (argument) and specify the number of ranked coins.

For example:

```
pycoinmon -t 1000
```
Shows top 1000 more relevant coins

**Comment by dArkjON** [comment]
Hey,
yeah -t 1000 is working nice but it gather all coins till 1000.

I was thinking the -f parameter can be used for only display the coins i like but i dont get get any info for a coin with a rank >100

**Comment by RDCH106** [comment]
-f parameter finds in response received from CoinMarketCap API and the limit for max coin number is defined by -t parameter. Then -f parameter find in result set returned by API limited by -t parameter.

First, request  and then filter is the tactic applied in this case.

**Comment by dArkjON** [comment]
Ahh great, thanks for your support it working nice now :+1:
